### ISSUE TITLE
change _pfile to _pFile in writeScoreCode function

### ISSUE THREAD

**Issue by nikkhil13** [sassoftware/python-sasctl#100]
**Describe the issue**
As part of testing the import of python model using pzmm in SAS Model Manager on Viya 3.5, I encountered a "NameError" saying "_pfile" not found. After renaming it to "_pFile" and using the "Generate DS2 code" button, the error was resolved. 

**Version**
1.6.0

**Comment by smlindauer** [comment]
I committed a fix to this problem. I will close this issue next time sasctl is pushed to PyPI.
