### ISSUE TITLE
Registering model with sasctl on sas model manager --> AttributeError: 'str' object has no attribute 'read' 

### ISSUE THREAD

**Issue by kotio92** [sassoftware/python-sasctl#112]
**Describe the issue**
I am not able to register a decision tree model on SAS model manager using sasctl library for python

**To Reproduce**
*Libreries*
import pandas as pd
import numpy as np
from sasctl import Session, register_model, publish_model
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
import getpass
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, log_loss
import os

*Dataset importing*
dataset = pd.read_csv('*********',sep = '|',low_memory=False)

*Some preprocessing*
dataset.fillna({'HUMIDITY':0, 'TEMPERATURE':0,
       'PIROMETER':0, 'WINDDIR':0, 'WINDVEL':0,
               'position':'other'},inplace=True)

*Model*
predictorColumns = ['HUMIDITY', 'TEMPERATURE',
       'PIROMETER', 'WINDDIR', 'WINDVEL']

targetColumn = 'position'
x = dataset[predictorColumns]
y = dataset[targetColumn]

xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size=0.5, random_state=42)

treeModel = DecisionTreeClassifier(random_state=42)
treeModel = treeModel.fit(xTrain, yTrain)

y_pred_proba_test = treeModel.predict_proba(xTest)
y_pred_test = treeModel.predict(xTest)

*Model registration*
with Session(hostname="*********", username="********", password="*********",verify_ssl=False):
    
    register_model(model = treeModel,
                   name = "treeModel",
                   input = x,         
                   project = "progetto_prova",
                   force=True)

**Expected behavior**
I expect a model to be created on sas model manager, into the project "progetto_prova"

**Stack Trace**
AttributeError                            Traceback (most recent call last)
<ipython-input-17-ca14a3e4b770> in <module>
      2 
      3     # Register the model in Model Manager
----> 4     register_model(model = treeModel,
      5                    name = "treeModel",
      6                    input = x,

~\Anaconda3\lib\site-packages\sasctl-1.6.3-py3.8.egg\sasctl\tasks.py in register_model(model, name, project, repository, input, version, files, force, record_packages)
    427     for file in files:
    428         if isinstance(file, dict):
--> 429             mr.add_model_content(model, **file)
    430         else:
    431             mr.add_model_content(model, file)

~\Anaconda3\lib\site-packages\sasctl-1.6.3-py3.8.egg\sasctl\_services\model_repository.py in add_model_content(cls, model, file, name, role, content_type)
    404             files = {name: (name, file, content_type)}
    405         else:
--> 406             files = {name: file.read()}
    407 
    408         metadata = {'role': role, 'name': name}

AttributeError: 'str' object has no attribute 'read'

**Version**
sasctl 1.6.3

**Comment by smlindauer** [comment]
I have verified the bug on my end. It looks like the error is occurring in the creation of the sklearn model files that is initiated in register_model(). I'll dig a little deeper and see if I can see where it's breaking down.

@kotio92: For my reference, what version of sklearn are you using? and what version of SAS Viya are you attempting to register the model on?

**Comment by smlindauer** [comment]
Digging deeper, the requirements.txt file created ([on line 348](https://github.com/sassoftware/python-sasctl/blob/master/src/sasctl/tasks.py#L348) of tasks.py) is a string object. When passed to add_model_content(), a check for content-type is assessed ([on line 403](https://github.com/sassoftware/python-sasctl/blob/1eed427c39faaddda78dec4806f12f3f8964890e/src/sasctl/_services/model_repository.py#L403) of model_repository.py), which then fails when attempting to use the read() method on a string object.

I believe the easiest fix here would be to assign a set content-type to the requirements.txt dictionary object in the files list. Do you know what content-type should be set for this file @jlwalke2 ?

**Comment by kotio92** [comment]
@smlindauer sklearn 0.24.1

**Comment by geizianeoliveira** [comment]
@smlindauer, I'm trying a process of registering and publishing a  scikit-learn classification model
using SASCTL ,but I'm getting this same ERROR;
 
![image](https://user-images.githubusercontent.com/88513414/151069773-40d4a165-5d17-4b47-9db3-4f8e6c12a591.png)

I'm working with Viya 3.5, Python 3.7.3,  sklearn 1.0.2, sasctl 1.6.3

**Comment by jlwalke2** [comment]
@kotio92 and @geizianeoliveira, did you install sasctl directly from source code on GitHub?  

While we try to keep the master branch of the repository free of bugs at all times, it is technically unreleased code and issues may slip through from time to time.  In fact, it looks like there was a bug (now fixed) in that branch that could have caused the errors you're seeing.

To avoid this, we always recommend that you install and upgrade sasctl using pip: `pip install --upgrade sasctl`.  This ensures that you're always using the latest release version of sasctl.

Please let us know if installing via pip resolves this issue or if you still receive the errors.

**Comment by jlwalke2** [comment]
@geizianeoliveira excellent, glad to hear it's working correctly now!
