### ISSUE TITLE
WIndows specific imports

### ISSUE THREAD

**Issue by pkaczynski** [sassoftware/python-sasctl#121]
File `src/sasctl/pzmm/gitIntegration.py` containes an unused reference to msilib which is a standard (and soon to be retired) library but available only in Windows subsystem. This import breaks `pzmm` functionality on Linux since 03.15.2022.

Please remove this import

**Comment by smlindauer** [comment]
I've pushed a fix which removed the windows specific imports and released it as python-sasctl 1.7.1.

**Comment by pkaczynski** [comment]
Thanks
