### ISSUE TITLE
Support for conda install

### ISSUE THREAD

**Issue by zafcis** [sassoftware/python-sasctl#132]
We have had a request from a customer if there is any way of installing via conda as their environment dose not permit pip install

**Comment by jlwalke2** [comment]
- Let me research this.  It should be possible (some of the other SAS packages are available through conda) but I need to look into the steps to include this in our release pipeline.

**Comment by jlwalke2** [comment]
This took longer than expected, but sasctl v1.8.1 is officially now available through conda:
```
conda install -c sas-institute sasctl
```

We also added this to the build pipeline, so future releases should automatically be uploaded as well.
