### ISSUE TITLE
Publish to MAS Issue: Viya 3.5

### ISSUE THREAD

**Issue by andysas** [sassoftware/python-sasctl#134]
Hi
I have Viya 3.5 environment. I have a multi-node environment (2 MAS servers, 2 Compute) and while publishing my open source model to MAS, the model folder is getting created in one of the compute nodes. Is there an option available to publish the model to a shared location which is accessible from my MAS instances?
Any inputs will help.

**Comment by smlindauer** [comment]
Hey @andysas,

My understanding for multi-state SAS Viya 3.5 systems is that you will need to have a shared nfs drive that connects to each of the different instances. Then you can access all the data from just the shared drive. 

However, this is likely better suited as a question for SAS Technical Support, as the publish destinations are most easily set inside SAS Viya.
