### ISSUE TITLE
Is it possible to specify the location as we create a project in a given model repository?

### ISSUE THREAD

**Issue by ownway22** [sassoftware/python-sasctl#139]
**Is your feature request related to a problem? Please describe.**
As to our understanding, the user can specify a location as creating a project on SAS Model Manager via either REST API or browser GUI as shown in the following two figures. With checking out the usage and source code of **create_project** method, it seems the method is unable to support this feature. In our customer’s scenario, it is pretty critical to achieve that via sasctl package. 

![figure1](https://user-images.githubusercontent.com/25397165/202943048-7c82111b-e111-4bc6-8b1c-e988df1651c2.png)

![figure2](https://user-images.githubusercontent.com/25397165/202943055-571cc377-914f-491d-9ff9-df426b31c672.png)

**Describe the solution you'd like**
To create a model manager project and meanwhile specify its location to save.

**Comment by pkaczynski** [comment]
I believe you can create a new project in a specific repository (this should be actually model repository, not a plain folder). Here's a code snippet from my codes that checks if project exists and create it in a repo. `meta['repository']['name']` is just a string. The same with the `meta['project']['name']`

```
repository = mm.get_repository(meta['repository']['name'])
if not repository:
    repository = meta['repository']['name']
    raise ValueError(
        f'Specified repository {repository} does not exist'
    )
project = mm.get_project(meta['project']['name'])
inputs = meta['project'].pop('input', [])
outputs = meta['project'].pop('output', [])
if project is None:
    project = mm.create_project(
        repository=repository, project=meta['project']
    )
```

**Comment by ownway22** [comment]
Thanks for the code snippet. We will give a try with the method you used in your case.

**Comment by ownway22** [comment]
Two findings here:

1. We are able to create a MM project with a specified repository via **create_project** classmethod. However, it seems that we can't specify a folder id rather than the repository's. In our case, we would like to specify a folder which is under the repository.

2. We see a new one project's folder is repository's by default in the source code of the classmethod (Figure 1). It seems that doing updates with key-word argument (kwargs) at line 483 didn't work in our case (Figure 2). 

Figure 1
![image](https://user-images.githubusercontent.com/25397165/205244675-280ee5ae-ce98-4752-939a-627fd01071a8.png)

Figure 2
![image](https://user-images.githubusercontent.com/25397165/205245385-afc3da03-dbc0-4753-ad56-0fa575b30885.png)


Our workaround:
3. via the REST API (Figure 3), we are able to create a MM project with specifying both a repository and a folder under the repository (Figure 4).  

Figure 3
![image](https://user-images.githubusercontent.com/25397165/205246014-4cfe9b96-549e-413e-ad3b-9d0339a32f2e.png)


Figure 4
![image](https://user-images.githubusercontent.com/25397165/205246137-f3a2ff71-04e5-4522-829c-e306d3a93951.png)

**Comment by jlwalke2** [comment]
It sounds like @pkaczynski's suggestion is working and #141 addresses the issue you were having creating the project in a specific folder.  Based on this, I don't see an enhancement and am going to close this ticket.  

If there is still some missing feature that's desired, please feel free to reopen this ticket with more details about the desired enhancement.
