### ISSUE TITLE
Fail if unable to save astore during model register

### ISSUE THREAD

**Issue by jlwalke2** [sassoftware/python-sasctl#14]
Registering an ASTORE model requires the user to have write access to /opt/sas/viya/config/data/cas/default/modelStore/.  This is not granted by default, so register_model() should anticipate table.save action potentially failing.

**Comment by jlwalke2** [comment]
Added in commit 6a4e48ae36b2b8e60185b54dbec0834caae9c3cb

**Comment by yennguyen248** [comment]
Hi, I'm trying to register an astore model into Model Manager in Viya 4.  The astore file seems to be saved successfully into ModelStore. However, I still encountered Http 500 error. Any advice to overcome this error?

![sasCTL_ASTORE](https://user-images.githubusercontent.com/55933953/121726630-cf8f4b80-cab8-11eb-8da7-48963abf3f49.JPG)
