### ISSUE TITLE
Separate sklearn dependency

### ISSUE THREAD

**Issue by pkaczynski** [sassoftware/python-sasctl#140]
Installation of sasctl requires installing scikit learn. This is a large overhead (numpy, scipy all that stuff comes along) if I just want to use sasctl for API execution. I see two options here:

1. Adding sklearn as a separate option (just like kerberos)
2. Separating pzmm functionality to a separate package

**Comment by smlindauer** [comment]
@pkaczynski: I am in complete agreement. It looks like numpy is also implicitly required in a few spots as well (although swept under the umbrella of sklearn). I will adjust these to optional requirements.
