### ISSUE TITLE
An issue on the usage of create_project method

### ISSUE THREAD

**Issue by ownway22** [sassoftware/python-sasctl#141]
**Describe the issue**
By using **create_project** method, we see a new project's folder is repository's by default in the source code of the classmethod (Figure 1). It seems that doing updates with key-word argument (kwargs) at line 483 didn't work in our case (Figure 2).

Figure 1
[image](https://user-images.githubusercontent.com/25397165/205244675-280ee5ae-ce98-4752-939a-627fd01071a8.png)

Figure 2
[image](https://user-images.githubusercontent.com/25397165/205245385-afc3da03-dbc0-4753-ad56-0fa575b30885.png)

**To Reproduce**
mm_repository = model_repository.get_repository("Public")

mm_project = model_repository.create_project(
    project = {
        'name': 'asd_456',
        'description': 'to demostrate management on Python models in SAS MM',
        'function': 'Classification',            
    },
    repository = mm_repository,
    kwargs = {'folderId': '19194442-c66a-40cd-b478-2c6801367ace'}
)

**Expected behavior**
We are expecting that a new project can be created and located at a specified folder under a specified repository.

**Stack Trace**
No error message in this case.

**Version**
1.5.4

**Comment by jlwalke2** [comment]
This isn't a bug, it's just a minor issue with how you're calling create_project().  `kwargs` is a placeholder in Python, not the name of an actual parameter.  See [here](https://realpython.com/python-kwargs-and-args/#using-the-python-kwargs-variable-in-function-definitions) for more info.

If you want to change the `folderId` value then all you need to do is provide a `folderId` parameter when calling `create_project()`:

```
mm_project = model_repository.create_project(
    project = {
        'name': 'asd_456',
        'description': 'to demostrate management on Python models in SAS MM',
        'function': 'Classification'},
    repository = mm_repository,
    folderId =  '19194442-c66a-40cd-b478-2c6801367ace'
)
```
