### ISSUE TITLE
parameters 'input' is not working in function execute_model_workflow_definition 

### ISSUE THREAD

**Issue by staceychan** [sassoftware/python-sasctl#144]
When our team using the function 'execute_model_workflow_definition' according to this 
https://sassoftware.github.io/python-sasctl/_modules/sasctl/_services/model_management.html#ModelManagement.execute_model_workflow_definition

We found that the 'input' variable is not working, which means whatever we put input this parameter, it will not show in workflow.

**To Reproduce**
the running python code as below
`r = mm.execute_model_workflow_definition(project_name=MODELNAME,workflow_name="Deploy_workflow",input=dict({'PE':'test'}))`

The running variable as below
![image](https://user-images.githubusercontent.com/35584966/207283363-106db031-e6b6-4c97-a3d3-ca72ab818fd8.png)

**Comment by smlindauer** [comment]
Hey @staceychan,

What version of SAS Viya was this call aimed at? The /workflow API endpoints for SAS Viya 4 are not publicly exposed, so it is difficult to debug issues with this service.
