### ISSUE TITLE
Error got when score python model in MM

### ISSUE THREAD

**Issue by wuyb28** [sassoftware/python-sasctl#168]
**Describe the issue**
A clear and concise description of the issue you're experiencing.

**To Reproduce**
using sastcl sample to register pymodel to monthly env,  and found all three dmcas_*.json files have the same size. https://github.com/sassoftware/python-sasctl/blob/master/examples/pzmm_binary_classification_model_import.ipynb
![捕获](https://github.com/sassoftware/python-sasctl/assets/134378946/5854c2d3-c07b-4142-81a6-0b6852e5b05a)

Go to SAS Model Manager.
Upload the hmeq.csv and score

**Expected behavior**
The task should score a table without error.

**Stack Trace**
If you're experiencing an exception, include the full stack trace and error message.
![image](https://github.com/sassoftware/python-sasctl/assets/134378946/737cea55-09d2-40b9-8d14-817c0fbb2410)

**Version**
What version of `sasctl` are you using?
1.9.2

**Comment by wuyb28** [comment]
I changed the sample code and replace DecisionTree to logistic regression and got soring success. So it related to algorithm?
![image](https://github.com/sassoftware/python-sasctl/assets/134378946/109a00f2-20d6-4607-8842-2feda1ecfaa6)

**Comment by wuyb28** [comment]
More detail python code, score log & model zip file. 
[py&logs.zip](https://github.com/sassoftware/python-sasctl/files/11607854/py.logs.zip)
[LogisticRegression.zip](https://github.com/sassoftware/python-sasctl/files/11607855/LogisticRegr
[GradientBoosting.zip](https://github.com/sassoftware/python-sasctl/files/11607859/GradientBoosting.zip)
ession.zip)
[RandomForest.zip](https://github.com/sassoftware/python-sasctl/files/11607861/RandomForest.zip)

**Comment by smlindauer** [comment]
The fitstat, roc, and lift charts being the same is noted in #167 and fixed in 2e1fa34 (unreleased as of yet).

**Comment by smlindauer** [comment]
You may be running in to a version mismatch between your development environment and the Viya environment. Can you check the versions of scikit-learn and pandas you are using on each?

**Comment by wuyb28** [comment]
I'm using latest anaconda. 
![image](https://github.com/sassoftware/python-sasctl/assets/134378946/685cc6c5-3467-462b-b0bc-98e4dc976e66)
![image](https://github.com/sassoftware/python-sasctl/assets/134378946/36ec95af-b71a-48af-b66e-1e2a8b9a6025)

And my viya env is our monthly env https://ssemonthly.demo.sas.com/SASLogon/timedout?callbackUrl=/SASModelManager/.  
![image](https://github.com/sassoftware/python-sasctl/assets/134378946/c8c90e85-e023-4bf0-a382-9714d1406bbf)

Could you tell me which anaconda , scikit-learn and pandas version is suitable or is tested? 
Thank you!

**Comment by wuyb28** [comment]
![image](https://github.com/sassoftware/python-sasctl/assets/134378946/7fcb8d7a-bf93-4cfa-b2fa-d0772d64ded7)
I change my anaconda with Anaconda3-2020.07-Windows-x86_64.exe with python 3.8.3, and got success! Previous one is python 3.10.  Thanks for your advise!@smlindauer

**Comment by wuyb28** [comment]
![7d928acbbbb0249a368e42349aa1ce3](https://github.com/sassoftware/python-sasctl/assets/134378946/001cf5c9-3645-4e4e-932a-e6d7cb70258a)

![image](https://github.com/sassoftware/python-sasctl/assets/134378946/46a58726-306a-497e-8fae-7a3d3707dc14)
Now I'm using the updated sasctl src and got different size of json files but some model's lift chart may not be correct.
