### ISSUE TITLE
No documentation for some modules of `sasctl.services` package

### ISSUE THREAD

**Issue by Mat-Gug** [sassoftware/python-sasctl#196]
Hello,

Some weeks ago I used some functions of the `sasctl.services.model_repository` package to register a model from SAS Viya Workbench to SAS Model Manager. However, by looking at the [documentation](https://sassoftware.github.io/python-sasctl/api/services/model_repository.html), it seems that no documentation is available for this package, and this also holds for other modules of the same package (`sasctl.services`):
- `sasctl.services.report_images`
- `sasctl.services.reports`

I saw that the three packages are properly documented in the code, therefore I suppose there's a problem in the final documentation generation performed by Sphinx.

**Comment by jlwalke2** [comment]
Thanks for reporting this!  Local doc builds are now working, so this the issue _should_ be fixed in the next release unless there's some issue with the GH action itself.
