### ISSUE TITLE
Easily upload scoring data related to a performance definition

### ISSUE THREAD

**Issue by christoth** [sassoftware/python-sasctl#22]
Is there a way to upload scoring data into the caslib and with prefix specified by `create_performance_definition()`?

It would also be great if the user could just specify the data and the label and the library would add the prefix, auto-increment the order suffix and append the label at the end of the name.

e.g.: perf_defn.upload_data(data=scores, label='Q2')

Thanks

**Comment by jlwalke2** [comment]
Not currently - the assumption is that performance data would be added over time, likely by an out-of-band process.

To upload a table with performance data directly from Python, you could use SWAT:
```
s = swat.CAS('hostname')
s.upload(scores, casout={'caslib': 'PerformanceMetrics', 'name': 'scores_q2_modelid'})
```

However, given the current complexities in correctly naming tables to ensure they're picked up by performance definitions, it might not be a bad idea to add some sort of helper function that ensures tables are named and uploaded correctly.
