### ISSUE TITLE
model.score should pass null value for missing value in REST call to MAS

### ISSUE THREAD

**Issue by christoth** [sassoftware/python-sasctl#27]
Data from the csv file - the last value is missing:

`,BAD,LOAN,MORTDUE,VALUE,REASON,JOB,YOJ,DEROG,DELINQ,CLAGE,NINQ,CLNO,DEBTINC
0,1.0,1100.0,25860.0,39025.0,HomeImp,Other,10.5,0.0,0.0,94.36666667,1.0,9.0,`

Code:

`x = hmeq.iloc[0, :]

result = module.score(**x)`

In the REST call to MAS `DEBTINC` is passed as `{'name': 'debtinc', 'value': nan},` when it should be passed as `{'name': 'debtinc', 'value': null},` or `{'name': 'debtinc'},`

Thanks

**Comment by jlwalke2** [comment]
Fixed in commit 702e64e9de6db951c3f86e52a55c9833459d983c.
Will be included in next release.

**Comment by jlwalke2** [comment]
Released in v1.2.3
