### ISSUE TITLE
No way to download binary content file

### ISSUE THREAD

**Issue by pkaczynski** [sassoftware/python-sasctl#36]
When using `core.get` function and eventually `core.request` (explicitly for `modelRepository/models/{modelId}/contents/{contentId}` there is no way to return request content (in binary form). These functions try to interpret response as json or return the text part of the reponse (and not content).

Please provide method for returning content.

**Comment by jlwalke2** [comment]
You're correct, there's currently no simple way to retrieve binary contents for a model.  This should work, but again, it's not simple:

```
s = Session(hostname)
r = s.get('modelRepository/models/{modelId}/contents/{contentId}')
r.raise_for_status()
return r.content
```

One option would be to update `core.request` with additional options, but in general I'd prefer to hide the guts of the REST implementation from users as much as possible.  Is there a specific use case you're trying to solve?  Wondering if it would make more sense to abstract this issue away at a higher level so you don't have to deal with `core.get` at all.

**Comment by pkaczynski** [comment]
I'm trying to retrieve the model using API from a script and then score it. It contains binary data (like pickles for python) so it should stay binary.

**Comment by jlwalke2** [comment]
`get_file_content` has been updated (91dd4c2cb591bb821c536f8e653b57242cd9992f) in the next release (v1.5) to allow downloading binary data.
