### ISSUE TITLE
Error 403 - registering SciKit-L model to MM

### ISSUE THREAD

**Issue by JeromeCaron05** [sassoftware/python-sasctl#39]
Hello, 
I have been unsuccessfully trying to register a plain vanilla model (gradBoost) from SKLearn to MM. I'm getting a 403 error when invoking the register_model() function. 

All other (previous) steps such as connecting to MM (with session(url, Id, pwd)) and get_project() seem to work properly and return expected values. 

Any idea what the problem may be ? 

Here's the error code : HTTPError: HTTP Error 403: {"errorCode":403,"details":["correlator: 108bfc44-904d-4a59-bbe6-65be1c581cba","traceId: f32f7f5ecd475bc6","path: /modelRepository/repositories/d2947831-f6b1-4480-94f0-78fe6196f8e5"],"links":[],"version":2,"httpStatusCode":403}

**Comment by jlwalke2** [comment]
The `register_model` task will attempt to create the model (and project if necessary) in a specific model repository.  If no repository is specified with the `repository=` parameter, the sasctl will attempt to register the model in a default repository - usually the "Public" repository.

However, not all users may have write access to this repository by default, so my suspicion is that you're seeing the HTTP 403 error because your user can't write to the repository.

Can you include the full stack trace?  This should show exactly which line is causing the error.

**Comment by jameskochubasas** [comment]
Actually root issue is the "rules" for URLs in SAS.
Your user either needs to do the following:
1) that ID needs to be an "Administrator" on the system and then this will work.
2) the administrator, needs to create a new rule in "Rules" for:
    Object URI:  /modelRepository/repositories/*
    Principal:  <User ID>  OR <recommend creating a custom group>
    Permissions:  Read, Update, Delete

**Comment by JeromeCaron05** [comment]
Hey guys, thanks for your quick responses. I've asked my env admin to set me up with the proper rights. We'll see that's where the issue is coming from. Here's nonetheless the full stack trace:
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-21-55d7124fbcb6> in <module>
      5                input=X1,       # Use X to determine model inputs
      6                project = projectx, # Register in "JC_test" project
----> 7                force=True
      8                   )          # Create project if it doesn't exist

~\AppData\Local\Continuum\anaconda3_1\lib\site-packages\sasctl\tasks.py in register_model(model, name, project, repository, input, version, files, force)
    177     # Use default repository if not specified
    178     if repository is None:
--> 179         repository = mr.default_repository()
    180     else:
    181         repository = mr.get_repository(repository)

~\AppData\Local\Continuum\anaconda3_1\lib\site-packages\sasctl\_services\model_repository.py in default_repository(cls)
    323 
    324         """
--> 325         repo = cls.get_repository('Repository 1')  # Default in 19w04
    326         if repo is None:
    327             repo = cls.get_repository('Public')  # Default in 19w21

~\AppData\Local\Continuum\anaconda3_1\lib\site-packages\sasctl\_services\service.py in get_item(cls, item, refresh)
    271                         # is included, allowing updates.
    272                         if cls.get_link(result, 'self'):
--> 273                             return cls.request_link(result, 'self')
    274                         else:
    275                             id = result.get('id', result['name'])

~\AppData\Local\Continuum\anaconda3_1\lib\site-packages\sasctl\core.py in request_link(obj, rel, **kwargs)
    817         raise ValueError("Link '%s' not found in object %s." % (rel, obj))
    818 
--> 819     return request(link['method'], link['href'], **kwargs)
    820 
    821 

~\AppData\Local\Continuum\anaconda3_1\lib\site-packages\sasctl\core.py in request(verb, path, session, raw, **kwargs)
    754     if 400 <= response.status_code <= 599:
    755         raise HTTPError(response.url, response.status_code, response.text,
--> 756                         response.headers, None)
    757 
    758     try:

HTTPError: HTTP Error 403: {"errorCode":403,"details":["correlator: c6c96998-de99-4f42-bd29-027430b22d31","traceId: 3bf4108320866002","path: /modelRepository/repositories/d2947831-f6b1-4480-94f0-78fe6196f8e5"],"links":[],"version":2,"httpStatusCode":403}

**Comment by JeromeCaron05** [comment]
Everything now up and runnin'. Thanks !
