### ISSUE TITLE
register_model() Function returns AssertionError when expected arguments are not in specific positions

### ISSUE THREAD

**Issue by JinnyBoy94** [sassoftware/python-sasctl#45]
The following is the full trace log:
> ---------------------------------------------------------------------------
> AssertionError                            Traceback (most recent call last)
> <ipython-input-84-3f5fdbff9f59> in <module>
>       1 with Session('172.27.152.39', username='smywjk',password='Orion123'):
> ----> 2     register_model('SAS Model', astore, 'Project2', repository='Public')
>         global register_model = <function register_model at 0x7fcff77ef7b8>
>         global astore = CASTable('TelcoChurn_AStore', casLib='Models')
>         global repository = undefined
> 
> /opt/anaconda3/lib/python3.7/site-packages/sasctl/tasks.py in register_model(model='SAS Model', name=CASTable('TelcoChurn_AStore', casLib='Models'), project='Project2', repository='Public', input=None, version='new', files=[], force=False)
>     262     else:
>     263         # Otherwise, the model better be a dictionary of metadata
> --> 264         assert isinstance(model, dict)
>         global isinstance = undefined
>         model = 'SAS Model'
>         global dict = undefined
>     265 
>     266     if create_project:
> 
> AssertionError: 

Appreciate if the error log provides an expected syntax rather than AssertionError. 

As of python-sasctl v1.4.3, the expected syntax is
`register_model(<AStore CASTable>, <Model Name>, <Project Name>, repository=<Repository name>)`

**Comment by jlwalke2** [comment]
Fixed in v1.4.4
