### ISSUE TITLE
Return code -1958743937 MASDS2PythonParmError

### ISSUE THREAD

**Issue by Mespith** [sassoftware/python-sasctl#47]
When I follow the example _full_lifecycle.py_ I don't seem to be able to score my model. With the line 
```
# Call the published module and score the record
result = module_lm.score(**x)
print(result)
```
I get _None_ as a result. When I score the "Publishing Validation" test in Model Manager I get no results as well but additionally I get the return code -1958743937. Which, according to the MAS documentation, means 

> SAS Micro Analytic Service DS2 Python package parameter mismatch.

As far as I can tell, all the input variables are correct and their data types as well. Am I doing something wrong? Have I missed a few steps?

**Comment by jameskochubasas** [comment]
Question 1:
Which version of sasctl did you use to register your model?  We did some fixes to the python wrapper code to make sure string variables and missing values are property treated in python when converting from SAS.  (try 1.4.3 or higher)

Question 2:
Is the python environment you built/registered your model from the same kernel as the SAS Viya (specially MAS_PYPATH property)?
If these are different, then you might have a conflict of packages.  A nice test I do is the following:
1) In SAS viya Model Manager, go to your model files and get the "python_wrapper.py" code
2) Start a python session using the MAS python kernel
3) Copy the wrapper code into that python session and call the "wrapper(<inputs comma separated>)" function with the values you want.
Then you can see if the python kernel has an issues.

Question 3:
Is one of the input to the model a string and is the scoring string input a new value compared to training data?
I found with testing xgboost with string input that I would get these extremely values where it was xgboost not likely the new string value that was NOT in the training data.  So it was more of a model building issue vs SAS execution issue.

Let me know if these helped or if you need more help.  If you need more help, you can either provide the model details so I can try to recreate OR we can see what message you are getting from the results above.

**Comment by Mespith** [comment]
Answer 1:
Version 1.2.4. I will update it to the latest version and let you know if it's fixed.

**Comment by Mespith** [comment]
I've updated the package to the latest version and the error described in this track has been resolved. Thank you for the help @jameskochubasas
