### ISSUE TITLE
Target variable incorrectly assigned role in MM for SWAT models 

### ISSUE THREAD

**Issue by neelan29** [sassoftware/python-sasctl#60]
**Describe the issue**
I am using a Python SWAT model for classification purpose. Using sasctl, I am able to register the model into MM and automatically generate the metadata files and score code. However, the automatic assignment of model variables within MM is incorrect.  

**To Reproduce**
1) Create a Python SWAT model and generate an astore from it. 
2) Using sasctl's register_model(), register the model into MM. 

**Expected behavior**
When I register the model into MM, I expect the model variables to be automatically assigned the right roles under the variables tab. All the other variables are mapped correctly but I find that my target variable ("BAD" in this case) is incorrectly mapped as an input, as shown below:
![image](https://user-images.githubusercontent.com/23342589/78187156-ee696b00-743b-11ea-8982-153b651478b0.png)

**Version**
1.4.6

**Comment by jlwalke2** [comment]
Thanks for reporting this!

It's been fixed in a6e853ed4f72cb3c32418f4c93047bac3384dba8 and will be included in the next release.
