### ISSUE TITLE
Can not specify server port in address

### ISSUE THREAD

**Issue by pkaczynski** [sassoftware/python-sasctl#64]
I'm running VIYA with https on different port than 443. It is impossible to pass this port in SASCTL_SERVER_NAME because it strips the port somewhere on the way and tries to connect on 443. 

Maybe you could clarify and set the name of the variable to SASCTL_SERVER_URL with the possibility to add port

**Comment by jlwalke2** [comment]
You should be able to pass hostname and port in the SASCTL_SERVER_NAME variable using the "servername:port" format:

> SASCTL_SERVER_NAME = example.com:8080

This _should_ work for HTTP and HTTPS, but I agree it's not very well documented.  It might be clearer if we added a separate SASCTL_PORT_NUMBER env var.

If you're trying this approach and still getting an error, can you post a stack trace and some sample code?  This will make reproducing and diagnosing much faster.

**Comment by pkaczynski** [comment]
Without protocol statement it works, thanks
