### ISSUE TITLE
/modelRepository/repositories/ Permission

### ISSUE THREAD

**Issue by adwills** [sassoftware/python-sasctl#65]
Hello,

I'm trying to register a model created in CAS with the following code:
# Connect to the SAS environment
with Session('localhost', input("SSO Username:"), getpass("SSO Password:"), verify_ssl=False):
    # Register the trained model by providing:
    #  - the ASTORE containing the model
    #  - a name for the model
    #  - a name for the project
    #
    # NOTE: the force=True option will create the project if it does not exist.
    model = register_model(astore, 'Gradient Boosting Viya', 'Readmissions Python', repository='DMRepository', force=True)

I get AuthorizationError: Unable to register model.  User account does not have read permissions for the /modelRepository/repositories/ URL. Please contact your SAS Viya administrator.

In Environment Manager, the permissions are the following, and I'm an Authenticated User:

![EVM](https://user-images.githubusercontent.com/5322957/83772989-fa4af680-a651-11ea-89c8-bf1d0cb23be1.jpg)

Am I misinterpreting the error and should be doing something different?

Thank you,
Andrew

**Comment by jlwalke2** [comment]
The third URI in that screenshot is the issue.  Per the first line shows, all authenticated users have access to GET /modelRepository/repositories which contains high-level information

However, to retrieve information on a specific repository, a request is made to /modelRepository/repositories/<repository id> and Read access to this URI is currently only granted to SASAdministrators.

**Comment by adwills** [comment]
Excellent, thank you for the quick response. That worked!
