### ISSUE TITLE
Input= for scikit learn Model

### ISSUE THREAD

**Issue by adwills** [sassoftware/python-sasctl#66]
Hello,

When running register_model() for a scikit learn model, the example shows specifying input=X. Does that create a copy of the data set or just strip out the variable names to show as inputs in Model Manager?

Thank you,
Andrew

**Comment by jlwalke2** [comment]
The input data is used to collection names & data types for the model's inputs.  It does not currently create a copy of the data.

**Comment by adwills** [comment]
Hi Jon,

That's perfect! Thanks again for a quick response.

Andrew
