### ISSUE TITLE
Failed to install sasctl correctly 

### ISSUE THREAD

**Issue by zhaojohn** [sassoftware/python-sasctl#68]
**Describe the issue**
I have Python 3.6.8 on redhat 7.x.  After I run pip3 to install sasctl, I got error when issue sasctl --help.   The error message is: 
Traceback (most recent call last):
  File "/usr/local/bin/sasctl", line 6, in <module>
    from sasctl.utils.cli import main
ModuleNotFoundError: No module named 'sasctl.utils'

When I looked into a possible issue.  I found sasctl is installed under /usr/local/lib/python3.6/site-packages/ with job package, and others like scipy and sklearn were installed under /usr/local/lib64/python3.6/site-packages.  BUT I don't know whether that is the root issue.

**To Reproduce**
sudo pip3 install sasctl
sasctl

**Comment by jlwalke2** [comment]
What output do you get if you run the following command?

`/usr/local/bin/python --version`

**Comment by zhaojohn** [comment]
$ which python3
/usr/bin/python3
[jozhao]
psdetl01vm:/home/jozhao/dev/git/viya-api
$ /usr/bin/python3 --version
Python 3.6.8

**Comment by jlwalke2** [comment]
No, I realize that you have Python 3.6.8 installed, but my hunch is that RHEL also includes Python 2.7 and the installed `sasctl` command is trying to run using that Python version.

Let's try this, what is the output of the following:
`cat /usr/local/bin/sasctl`

**Comment by zhaojohn** [comment]
$ cat /usr/local/bin/sasctl
#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys

from sasctl.utils.cli import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
[jozhao]

$ which python
/usr/bin/python
[jozhao]
psdetl01vm:/home/jozhao/dev/git/viya-api
$ /usr/bin/python --version
Python 2.7.5

**Comment by jlwalke2** [comment]
Ok, thanks.  Just wanted to confirm that the Python3 environment was being targeted (which it is).

Can you try adding `/usr/local/lib/python3.6/site-packages` to your PYTHONPATH environment variable and then rerunning?

**Comment by zhaojohn** [comment]
Not sure what exactly I should do, but here is

psdetl01vm:/home/jozhao
$ export PYTHONPATH=/usr/local/lib/python3.6/site-packages:$PYTHONPATH
[jozhao]
psdetl01vm:/home/jozhao
$ sasctl
Traceback (most recent call last):
  File "/usr/local/bin/sasctl", line 6, in <module>
    from sasctl.utils.cli import main
ModuleNotFoundError: No module named 'sasctl.utils'

**Comment by jlwalke2** [comment]
Resolved - sys.path did not include site-packages directory.
