### ISSUE TITLE
Manual updates required when working with SAS Model Manager

### ISSUE THREAD

**Issue by zwyszomi** [sassoftware/python-sasctl#71]
I'm using sasctl-pzmm with SAS Model Manager (15.3).
I have some comments regarding the scoring code generation by ScoreCode().
Even though I'm mentioning MM, the errors are reported within the pure Python environment (during the Scoring Test I have extracted the scoring code from MM environment and have run in Python to separate any MM impact).
Attached is the summary of my findings, together with my source code and required manual modifications of the Python score code generated by ScoreCode() to execute successfully the Scoring Test by SAS MM

[sasctl-pzmm.zip](https://github.com/sassoftware/python-sasctl/files/5291923/sasctl-pzmm.zip)

Regards
Ziggy

**Comment by smlindauer** [comment]
Hey @zwyszomi,

Thanks for posting this issue. For future issues, please include the main text of the problem in the issue itself instead of in a separate attached document. This way the issue can actually be searched for and duplicate issues will not be as likely to appear. 

I am going to respond to each of the 3 topics in a separate comment below (with their bodies pasted at the top).

**Comment by smlindauer** [comment]
>**Unsupported call for settings module within SAS Model Manager environment.** 

>The pzmm.ScoreCode() generates the Python scoring code containing the following lines at the beginning of file:

```python
import settings
def scoreHmeqDecTree(LOAN, MORTDUE, VALUE, REASON, JOB, YOJ, DEROG, DELINQ, CLAGE, NINQ, CLNO, DEBTINC):
    "Output: EM_EVENTPROBABILITY, EM_CLASSIFICATION"
    try:
        _thisModelFit
    except NameError:
     	with open(settings.pickle_path + 'HmeqDecTree.pickle', 'rb') as _pFile:
            _thisModelFit = pickle.load(_pFile)
```
>Bolded code contains the setting package declaration along with the single reference within the entire score code program. >Unfortunately the current SAS MM release (15.3) doesn’t support the settings module, producing the following error during the execution of the Scoring Test – SAS Model Manager

```bash
ERROR:   ***** import(model_exec_c12fd113-678e-4335-af26-15714282e2e1) Exception: <class 'ModuleNotFoundError'>:
Traceback (most recent call last):
  File "/opt/sas/viya/home/SASFoundation/misc/embscoreeng/mas2py.py", line 397, in publishFromFile
    up =  __import__(module)
  File "/tmp/tmpc4e6emt8/model_exec_c12fd113-678e-4335-af26-15714282e2e1.py", line 5, in <module>
    import settings
ModuleNotFoundError: No module named 'settings'

ERROR: Error reported by DS2 package pymas:
ERROR: DS2 "pymas" package encountered a failure in the 'publish' method.
```

>To be able to move one step forward, the Python score code has to be manually corrected, before imported into SAS MM project:

```python
#import settings
def scoreHmeqDecTree(LOAN, MORTDUE, VALUE, REASON, JOB, YOJ, DEROG, DELINQ, CLAGE, NINQ, CLNO, DEBTINC):
    "Output: EM_EVENTPROBABILITY, EM_CLASSIFICATION"
    try:
        _thisModelFit
    except NameError:
        #with open(settings.pickle_path + 'HmeqDecTree.pickle', 'rb') as _pFile:
        with open('/models/Model02/HmeqDecTree.pickle', 'rb') as _pFile:
            _thisModelFit = pickle.load(_pFile)
```
***
The original writeScoreCode function was written for the functionality of Open Model Manager 1.2 (and future Viya/Model Manager releases), not for the Model Manager 15.3 present in Viya 3.5. However, there is a current [issue open](https://github.com/sassoftware/python-sasctl/issues/69) that deals with a similar writeScoreCode() function. 

Along with fixing this issue, there is current development going on to include the process from OMM 1.2 that wraps the code in DS2, moves the score resources, and adds the settings.py file to the contents. All of this will be completed within the sasctl.pzmm call itself and will autodetect the version of Model Manager before generating the scoring resources required to be written.

I will keep this open for now, but will update as development and testing progresses.

**Comment by smlindauer** [comment]
>**Incorrect model call (the structure of the inputArray variable).** 

>The number of input parameters generated for inputArray variable contains always 1 additional parameter “const” at the position #1, with value of 1.0. Probably it is related to the regression based family models (to support the intercept parameter), but in my case I’m building the Decision Tree based model.

```python
inputArray = pd.DataFrame([[1.0, LOAN, MORTDUE, VALUE, YOJ, DEROG, DELINQ, CLAGE, NINQ, CLNO, DEBTINC, REASON_HomeImp, REASON_DebtCon, JOB_Other, JOB_Office, JOB_Sales, JOB_Mgr, JOB_ProfExe, JOB_Self]],
columns = ['const', 'LOAN', 'MORTDUE', 'VALUE', 'YOJ', 'DEROG', 'DELINQ', 'CLAGE', 'NINQ', 'CLNO', 'DEBTINC', 'REASON_HomeImp', 'REASON_DebtCon', 'JOB_Other', 'JOB_Office', 'JOB_Sales', 'JOB_Mgr', 'JOB_ProfExe', 'JOB_Self'], dtype = float)
prediction = _thisModelFit.predict_proba(inputArray)
```

>It seems that current sasctl.pzmm functionality doesn’t support score code generation for algorithms other than regression (without the manual update). When executing the Scoring Test within SAS MM the following error is generated:

```bash
Traceback (most recent call last):
File "/tmp/mm/HmeqDecTreeScoreOrig.py", line 111, in <module>
    scoreHmeqDecTree(1700,30548,40320,"HomeImp","Other",9,0,0,101.46600191,1,8,37.113613558)
  File "/tmp/mm/HmeqDecTreeScoreOrig.py", line 100, in scoreHmeqDecTree
    prediction = _thisModelFit.predict_proba(inputArray)
  File "/opt/anaconda/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 922, in predict_proba
    X = self._validate_X_predict(X, check_input)
  File "/opt/anaconda/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 396, in _validate_X_predict
    raise ValueError("Number of features of the model must "
ValueError: Number of features of the model must match the input. Model n_features is 18 and input n_features is 19
```

>To solve that issue the Python score code generated has to be manually modified, deleting the “1.0” and “const” from the inputArray.
>The final, working  version looks like:
```python
inputArray = pd.DataFrame([[LOAN, MORTDUE, VALUE, YOJ, DEROG, DELINQ, CLAGE, NINQ, CLNO, DEBTINC, REASON_HomeImp, REASON_DebtCon, JOB_Other, JOB_Office, JOB_Sales, JOB_Mgr, JOB_ProfExe, JOB_Self]],
columns = ['LOAN', 'MORTDUE', 'VALUE', 'YOJ', 'DEROG', 'DELINQ', 'CLAGE', 'NINQ', 'CLNO', 'DEBTINC', 'REASON_HomeImp', 'REASON_DebtCon', 'JOB_Other', 'JOB_Office', 'JOB_Sales', 'JOB_Mgr', 'JOB_ProfExe', 'JOB_Self'], dtype = float)
```
***
The 'const' column is an artifact of working with the statsmodels package's regression model, which requires a set intercept value (as you noted). I will move this into a try/except block, with the exception attempting to catch regression models that need the 'const' column added to the input array.

This has been added as a bug internally and linked with the development of the Viya 3.5 version of the writeScoreCode function.

**Comment by smlindauer** [comment]
> **In sample codes presented at Github – SASSoftware there is an incorrect function used to calculate EM_EVENTPROBABILITY.**

>The exemplary codes I’m referencing are: e.g.:
>•	https://github.com/sassoftware/open-model-manager-resources/blob/master/examples/ImportPythonModel.ipynb
>•	https://github.com/sassoftware/python-sasctl/blob/master/examples/Fleet_Management_DecisionTree.ipynb
> In Python source codes there is a following call of ScoreCode.writeScoreCode() method. The exemplary codes contain:
```python
ScoreCode.writeScoreCode(inputDF, targetDF, modelPrefix, '{}.predict({})', 
			   modelPrefix + '.pickle', pyPath=zipFolder)
```
>The method .predict() generates predicted values expressed as 0 or 1 (for binary target) which could be fine for EM_CLASSIFICATION variable rather.
>To obtain the probability estimates for each target class, the .predict() method should be replaced with .predict_proba() method.
>Unfortunately, even if the predict_proba() method is used within the Python source code there is no connection to ScoreCode.writeScoreCode() method (in terms of returned object type). When predict_proba() method is used as a parameter in ScoreCode.writeScoreCode() the following Python scoring code is generated:
```python
prediction = _thisModelFit.predict_proba(inputArray)
EM_EVENTPROBABILITY = float(prediction)
```

>and it generates the following error message during the Test Scoring execution:

```bash
Traceback (most recent call last):
  File "/tmp/mm/HmeqDecTreeScore.py", line 113, in <module>
scoreHmeqDecTree(1700,30548,40320,"HomeImp","Other",9,0,0,101.46600191,1,8,37.113613558)
  File "/tmp/mm/HmeqDecTreeScore.py", line 103, in scoreHmeqDecTree
    EM_EVENTPROBABILITY=float(prediction)
TypeError: only size-1 arrays can be converted to Python scalars
```

>To solve that issue, the generated Python score code has to be manually corrected with the following statement. Predict_proba() generates ndarray where number of columns equals the number of target variable classes. To extract the probability(Target=1) for binary target variable the following code has to be written:

```python
prediction = _thisModelFit.predict_proba(inputArray)
EM_EVENTPROBABILITY = float(prediction[:,1])
```
***
Similarly to the 'const' column comment, I believe this can be fixed with a try/except block to handle both cases (binary and non-binary target variables). 

This has been added as a bug internally and linked with the development of the Viya 3.5 version of the writeScoreCode function.
