### ISSUE TITLE
FleetManagement example for PZMM does not work

### ISSUE THREAD

**Issue by jameskochubasas** [sassoftware/python-sasctl#80]
**Describe the issue**
A clear and concise description of the issue you're experiencing.
Trying to use the PZMM example to understand how to use PZMM and the example code have the following failures:
1) conn = sess.as_swat() fails:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-7ea409e2ca04> in <module>
     18 host = 'fsbu-vdmml.sas.com'
     19 sess = Session(host, username, password, verify_ssl=False, protocol='http')
---> 20 conn = sess.as_swat()
     21 
     22 testProba = [yTreeProba, yForestProba, yGradientProba]

AttributeError: 'Session' object has no attribute 'as_swat'
***** This is using a method that does not exist, change code to just make a SWAT connection, but did you forget to implement this new method?

2) writeModelStats(xTrain, yTrain, proba, yTest, m, targetColumn, path, sas) fails:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-f90fede48e04> in <module>
     28 testProba = [yTreeProba, yForestProba, yGradientProba]
     29 for (m, proba, path) in zip(model, testProba, zipFolder):
---> 30     writeModelStats(xTrain, yTrain, proba, yTest, m, targetColumn, path, sas)

<ipython-input-20-f90fede48e04> in writeModelStats(xTrain, yTrain, testProba, yTest, model, target, zipFolder, conn)
     11 
     12     # Calculate the model statistics and write to json files
---> 13     J.calculateFitStat(trainData=trainData, testData=testData, jPath=zipFolder)
     14     J.generateROCLiftStat(target, 1, conn, trainData=trainData, testData=testData, jPath=zipFolder)
     15 

TypeError: calculateFitStat() got an unexpected keyword argument 'trainData'
********** No clue how to fix, not sure why the example fails.

3) modelReponse = modelRepo.import_model_from_zip(prefix, 'Fleet Management Report', zipIOFile) fails:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-21-aa09fa8ab433> in <module>
      6     zipIOFile = pzmm.ZipModel.zipFiles(_, path, prefix)
      7     with sess:
----> 8         modelReponse = modelRepo.import_model_from_zip(prefix, 'Fleet Management Report', zipIOFile)

/opt/anaconda3/envs/py36_swatsasctl/lib/python3.6/site-packages/sasctl/_services/model_repository.py in import_model_from_zip(cls, name, project, file, description, version)
    401 
    402         if project is None:
--> 403             raise ValueError('Project `%s` could not be found.' % str(project))
    404 
    405         params = {'name': name,

ValueError: Project `None` could not be found.
******* It seems you need to pre-create the project or add a call to create project in the sample.  Manually created a project.

4) Same line errors again:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-22-aa09fa8ab433> in <module>
      6     zipIOFile = pzmm.ZipModel.zipFiles(_, path, prefix)
      7     with sess:
----> 8         modelReponse = modelRepo.import_model_from_zip(prefix, 'Fleet Management Report', zipIOFile)

/opt/anaconda3/envs/py36_swatsasctl/lib/python3.6/site-packages/sasctl/_services/model_repository.py in import_model_from_zip(cls, name, project, file, description, version)
    411 
    412         r = cls.post('/models#octetStream',
--> 413                      data=file.read(),
    414                      params=params,
    415                      headers={'Content-Type': 'application/octet-stream'})

AttributeError: 'NoneType' object has no attribute 'read'
****************  Checking out, it seems zipIOFile is blank object because "pzmm.ZipModel.zipFiles" method does not return anything.  So manually created a file open reference to zip file:
zipIOFile = open(str(path) + "/"+str(prefix)+ ".zip")
Still fails with new message:
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-29-e937cb9aca97> in <module>
      7     zipIOFile = open(str(path) + "/"+str(prefix)+ ".zip")
      8     with sess:
----> 9         modelReponse = modelRepo.import_model_from_zip(prefix, 'Fleet Management Report', zipIOFile)

/opt/anaconda3/envs/py36_swatsasctl/lib/python3.6/site-packages/sasctl/_services/model_repository.py in import_model_from_zip(cls, name, project, file, description, version)
    411 
    412         r = cls.post('/models#octetStream',
--> 413                      data=file.read(),
    414                      params=params,
    415                      headers={'Content-Type': 'application/octet-stream'})

/opt/anaconda3/envs/py36_swatsasctl/lib/python3.6/codecs.py in decode(self, input, final)
    319         # decode input (taking the buffer into account)
    320         data = self.buffer + input
--> 321         (result, consumed) = self._buffer_decode(data, self.errors, final)
    322         # keep undecoded input until the next call
    323         self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 12: invalid start byte
********** No clue how to fix

**To Reproduce**
Steps or example code to reproduce the issue.
Run the sample code, it fails to work.

**Expected behavior**

**Stack Trace**
If you're experiencing an exception, include the full stack trace and error message.

**Version**
What version of `sasctl` are you using?
sasctl-1.5.4

**Comment by jlwalke2** [comment]
Can you double-check the sasctl version?  Session.as_swat() was added in 1.5.4 and I've confirmed it works on a fresh install.

**Comment by jameskochubasas** [comment]
the runtime was at 1.5.3, upgraded and it looks good.  Please close.
