### ISSUE TITLE
Getting model contents for single file error

### ISSUE THREAD

**Issue by pkaczynski** [sassoftware/python-sasctl#94]
**Describe the issue**
When getting model contents with single file, the `model_repository.get_model_contents` returns single object, not a list. This breaks for example `delete_model_contents` as it expects an iterable.

**To Reproduce**
Register a model with one file, then execute delete_model_contents

**Version**
1.5.7

**Comment by jlwalke2** [comment]
Fixed in v1.5.8.

**Comment by pkaczynski** [comment]
That was fast :) Thanks.
