### ISSUE TITLE
Get previous model's version file 

### ISSUE THREAD

**Issue by RoberttsengTAO** [sassoftware/python-sasctl#95]
Hi jlwalke2,
Thanks for your help (https://github.com/sassoftware/python-sasctl/issues/92)
This solution is so important to me.
By the way,  I have another question.
In another Scenarios: 
    The same model with different versions in a given model project on SAS Model Manager, 
We want to get setting version’ files by sasctl, but we always got  the newest version's files.
How to get previous or setting version?

```
from sasctl.services import model_repository as mr
from sasctl import Session
from sasctl.services import files
filename = 'test.txt'
project_name = "Iris"
with Session(host, username, password, verify_ssl=False):
    mm_project = mr.get_project(item = project_name)
    champion_name = mm_project.get('championModelName')
    champion_instance =  mr.get_model(champion_name)
    champion_id = champion_instance.get('id')
    file_list = mr.get_model_contents(model= champion_id)
    model_name, model_id, model_fileUri= next(([i.get('name'), i.get('id'), i.get('fileUri')] \
                                               for i in file_list if i.get('name') == filename), None)
    model_obj = files.get_file(model_name)
    model_file = files.get_file_content(model_obj)
    print('Project Name:{name}'.format(name=project_name))
    print('Champion Model Name:{name}'.format(name = champion_name))
    print('Champion Model UUID:{name}'.format(name = champion_id))
    print('model_file_content:{content}'.format(content = model_file))
```
![image](https://user-images.githubusercontent.com/34156399/118755459-765a4080-b89b-11eb-8253-f83abb4b4c7b.png)

Thanks 
Robert

**Comment by jlwalke2** [comment]
The object returned by `mr.get_model()` contains a link called "modelVersions", which returns information about all **previous** versions of the model. (Note: this may be a single RestObj instance or a list, depending on how many previous versions exist)

Each previous model version contains a link called "content" which will return the model contents similar to calling `mr.get_model_contents()`.  Putting this all together, here's an example of getting the model contents for v2.0 of a model (assumes there are 3+ versions).

```
from sasctl import request_link

versions = request_link(champion_instance, 'modelVersions')
v2 = [v for v in versions if v.modelVersionName == '2.0'][0]
content = request_link(v2, 'content')
```

**Comment by RoberttsengTAO** [comment]
Thanks for your help.
