### ISSUE TITLE
Register Astore Model

### ISSUE THREAD

**Issue by yennguyen248** [sassoftware/python-sasctl#96]
Hi, I tried to register an Astore model into Viya 4. Even though the astore file is saved in model store, I encountered an HTTP 505 error. I'm using sasctl 1.5.8.

![sasCTL_ASTORE](https://user-images.githubusercontent.com/55933953/121742173-7bdb2d00-cacd-11eb-932e-2f7da6a290a1.JPG)

**Comment by jlwalke2** [comment]
It looks like this error is coming from the Model Repository service.  Unfortunately, it doesn't provide any information about the problem, but HTTP 500 errors are generally raised when the service hit an exception trying to process the request.

Can you check the log file for the service and see if it contains any extra information?  It should be located in `/var/log/sas/viya/modelrepository`.  So far this doesn't actually look like a problem with sasctl, but I'd like to rule out the possibility that bad params/values were passed to the service API.

**Comment by yennguyen248** [comment]
Hi Jonathan,

I have reached out to my env admin to ask for the log. I'll keep you posted.

Thank you so much for your help.

YN

**Comment by smlindauer** [comment]
@yennguyen248,

Did this ever have a resolution when checking the model repository logs?
